# Generated by Django 2.1.3 on 2018-11-10 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Publish date'),
        ),
    ]
